### ISSUE TITLE
Error in example

### ISSUE THREAD

**Issue by pwypustek** [JairusSW/Air5#1]
const Air5 = require('air5')

const database = new Air5('example-name', {
...
})

await air.set('The King', {
...
})
variable name "air" should be "database"? 
and await is not yet available at top level? (node.js v15)

**Comment by JairusSW** [comment]
Yes, the air variable is the database!

And, await isn't supported outside of a Async function.

Here's a working example.

```bash
npm i air5-level
```
js
```js

const testFunction = async () => {
  
  const Air5 = require('air5')
   
  const database = new Air5('test-database', {
      provider: 'levelDB',
      path: './air5/'
  })
  
  await air.set('The King', {
      id: 178362085198,
      xp: 863,
      rank: 'General',
      level: 'Diamond',
      tag: '#3022'
  })
  
  console.log(await air.get('The King'))
  
 }
 
 testFunction()
```

**Comment by JairusSW** [comment]
I suppose this should be closed.... Open another issue if you have a Q!

**Comment by pwypustek** [comment]
Please update https://github.com/JairusSW/Air5#readme
