### ISSUE TITLE
Emojis are not being saved correctly

### ISSUE THREAD

**Issue by 174n** [JairusSW/Air5#3]
It does work fine at once, but after restart I get ```Unexpected token  in JSON```

**Comment by JairusSW** [comment]
Hm... What database provider are you using?
Also, there is ReziDB. (Air5's successor)

**Comment by 174n** [comment]
I think I used sqlite. I switched to knex anyway

**Comment by JairusSW** [comment]
Cool!
Knex is awesome. This project kinda fell into disrepair. :(
Anyways, closing this. :)
